version: "3.9"
services:
  db:
    image: "clickhouse/clickhouse-server"
    ports:
      - "18123:8123"
      - "19000:9000"
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"
    volumes:
      - "./config/clickhouse/default.xml:/etc/clickhouse-server/users.d/default.xml"
