receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 12000
    send_batch_max_size: 40000
    timeout: 4s
  memory_limiter:
    check_interval: 1s
    limit_mib: 8192
    spike_limit_mib: 1638

exporters:
  clickhouse:
    dsn: tcp://default:test123@db:9000/default
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [clickhouse]
